openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operation.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-5-kxqa.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/path/contacts/get.yaml
    post:
      $ref: ../swagger/path/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/path/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{id}/delete.yaml
  /register:
    post:
      $ref: ../swagger/path/auth/register.yaml
  /login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml
  /refresh:
    post:
      $ref: ../swagger/path/auth/refresh.yaml
  /request-reset-email:
    post:
      $ref: ../swagger/path/auth/registerUserPassword.yaml
  /reset-pwd:
    post:
      $ref: ../swagger/path/auth/resetPassword.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
